name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-gnu, x86_64-pc-windows-gnu

      - name: Install Cross
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Build for Linux x86_64
        run: cross build --release --target x86_64-unknown-linux-gnu

      - name: Build for Windows x86_64
        run: cross build --release --target x86_64-pc-windows-gnu

      - name: Prepare release assets
        run: |
          mkdir artifacts
          cp target/x86_64-unknown-linux-gnu/release/refield artifacts/refield-linux-amd64
          cp target/x86_64-pc-windows-gnu/release/refield.exe artifacts/refield-windows-amd64.exe

      - name: Generate release notes
        run: |
          echo "# Release Notes" > artifacts/RELEASE_NOTES.md
          echo "- Linux (amd64) and Windows (x86_64) binaries included." >> artifacts/RELEASE_NOTES.md

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/refield-linux-amd64
            artifacts/refield-windows-amd64.exe
            artifacts/RELEASE_NOTES.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
