name: Release Binaries

on:
  push:
    tags:
      - "v*"  # Trigger only on version tags like v1.0.0

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            bin_suffix: ""
            artifact_name: refield-linux-amd64
          - os: macos-latest
            target: aarch64-apple-darwin
            bin_suffix: ""
            artifact_name: refield-mac-arm64
          - os: windows-latest
            target: x86_64-pc-windows-gnu
            bin_suffix: ".exe"
            artifact_name: refield-windows-amd64

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust target
        run: rustup target add ${{ matrix.target }}

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Rename binary
        run: mv target/${{ matrix.target }}/release/refield${{ matrix.bin_suffix }} ${{ matrix.artifact_name }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.artifact_name }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: "refield-*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
